### PR TITLE
add FIC 0/7

### LINKED ISSUE #42: Add FIC 0/7
The standard EN 300 401 version 2 mandates that FIG 0/7 gets sent right after FIG 0/0.

Anybody interested in tackling this to add complete v2 support to ODR-DabMux?

- Decide what to make configurable and what not
- Define how to handle the "count" field. It adds state to the multiplexer across restarts!
- Check all FICs mentioned in TS 101 756v2.3.1 annex D

### PR DESCRIPTION
**Pull request by KuntzeM**
Fixes #42 

- add FIC 0/7 and send with 96ms like FIC 0/0
- reconfiguration counter is changable in mux file with "reconfig-counter" in ensemble part
- tested with several FIG 2 test mux

### CODE REVIEW

**Comment by mpbraendli** [comment]
Hello, this is great, thanks a lot!

One question: In EN 300 401 Clause 6.4.2, the location of FIG 0/7 is defined as follows:

> The FIG 0/7 shall be transmitted in the same FIB as the FIG 0/0 and shall be the second FIG in the FIB.

`FIGCarousel.cpp` line 270 does some special handling of FIG 0/0, to ensure it is at the fixed time position. Do we need to include special handling of FIG0/7?

Two things:

The `find_if` is now misleading, because FIG 0/0 is not the only FIG with rate `FIG0_0` anymore. I think it shouldn't filter of the rate, it should filter on the figtype and figextension.

And I would propose to modify the `carousel` function to ensure FIG 0/7 is transmitted immediately after FIG 0/0.

Do you agree with these proposed changes?

**Comment by mpbraendli** [comment]
As an aside remark: the travis build fails because of some Mac OSX build issue. I've opened #44 to track that one.

**Comment by KuntzeM** [comment]
Thank you :)
Because the Mac OSX build, I was a little bit confused :D

You are right with this handling. 
I change the condition to 
```
auto fig0_0 = find_if(sorted_figs.begin(), sorted_figs.end(),
            [](const FIGCarouselElement* f) {
            return (f->fig->figtype() == 0 && f->fig->figextension() == 0);
            });
```
I will copy the "FIG 0/0 special handling" part and paste it after them with changed values for FIG 0/7.

Now I can see, after every FIG 0/0 is send a FIG 0/7:
```
[08:10:48.146] FIG 0/00 05 00 d1 23 31 a6                                                                         ...#1. 
[08:10:48.146] FIG 0/07 03 07 1b d0                                                                               .... 
[08:10:48.146] FIG 0/01 05 01 25 e0 80 60                                                                         ..%..` 
[08:10:48.146] FIG 0/08 0d 08 a0 03 00 04 a0 04 00 05 a0 06 00 07                                                 .............. 
[08:10:48.146] FIG 0/02 1a 02 a0 02 01 3f 0e a0 03 01 3f 12 a0 04 01 3f 16 a0 06 01 3f 1e a0 07 01 3f 22          .....?....?....?....?....?" 
[08:10:48.146] FIG 0/02 06 02 a0 08 01 3f 26                                                                      .....?& 
[08:10:48.146] FIG 0/01 15 01 0c 00 80 60 10 60 80 60 14 c0 80 60 1d 20 80 60 21 80 80 60                         .....`.`.`...`. .`!..` 
[08:10:48.146] FIG 0/01 05 01 25 e0 80 60                                                                         ..%..` 
[08:10:48.156] FIG 2/01 52 09 a0 06 00 d8 a7 d9 84 d9 85 d8 a4 d8 aa d9 85 d8 b1                                  R.................. 
[08:10:48.156] FIG 0/09 04 09 02 e0 01                                                                            ..... 
[08:10:48.156] FIG 0/02 1a 02 a0 02 01 3f 0e a0 03 01 3f 12 a0 04 01 3f 16 a0 06 01 3f 1e a0 07 01 3f 22          .....?....?....?....?....?" 
[08:10:48.156] FIG 0/02 06 02 a0 08 01 3f 26                                                                      .....?& 
[08:10:48.156] FIG 0/01 15 01 0c 00 80 60 10 60 80 60 14 c0 80 60 1d 20 80 60 21 80 80 60                         .....`.`.`...`. .`!..` 
[08:10:48.156] FIG 0/01 05 01 25 e0 80 60                                                                         ..%..` 
[08:10:48.156] FIG 2/01 52 09 a0 07 00 d8 a7 d9 84 d9 82 d8 a7 d8 a6 d9 85 d8 a9                                  R.................. 
[08:10:48.156] FIG 0/09 04 09 02 e0 01                                                                            ..... 
[08:10:48.156] FIG 0/02 1a 02 a0 02 01 3f 0e a0 03 01 3f 12 a0 04 01 3f 16 a0 06 01 3f 1e a0 07 01 3f 22          .....?....?....?....?....?" 
[08:10:48.156] FIG 0/02 06 02 a0 08 01 3f 26                                                                      .....?& 
[08:10:48.166] FIG 0/01 15 01 0c 00 80 60 10 60 80 60 14 c0 80 60 1d 20 80 60 21 80 80 60                         .....`.`.`...`. .`!..` 
[08:10:48.166] FIG 0/01 05 01 25 e0 80 60                                                                         ..%..` 
[08:10:48.166] FIG 2/01 50 09 a0 08 00 d9 8a d8 aa d8 ad d8 af d9 91 d8 ab                                        P................ 
[08:10:48.166] FIG 0/08 05 08 a0 07 00 08                                                                         ...... 
[08:10:48.166] FIG 0/02 1a 02 a0 02 01 3f 0e a0 03 01 3f 12 a0 04 01 3f 16 a0 06 01 3f 1e a0 07 01 3f 22          .....?....?....?....?....?" 
[08:10:48.166] FIG 0/02 06 02 a0 08 01 3f 26                                                                      .....?& 
[08:10:48.166] FIG 0/01 15 01 25 e0 80 60 21 80 80 60 1d 20 80 60 14 c0 80 60 10 60 80 60                         ..%..`!..`. .`...`.`.` 
[08:10:48.246] FIG 0/00 05 00 d1 23 31 aa                                                                         ...#1. 
[08:10:48.246] FIG 0/07 03 07 1b d0                                                                               .... 
[08:10:48.246] FIG 0/01 05 01 0c 00 80 60                                                                         .....` 
[08:10:48.246] FIG 0/08 05 08 a0 08 00 09  
```

**Comment by mpbraendli** [comment]
Thanks! I'll merge it and simplify the carousel a bit.

I will also make the FIG0/7 optional (e.g. through the absence of the configuration entry) because in operations you want to be able to enable/disable this without changing software version.

Then I'll ask you to test it again.

**Comment by mpbraendli** [comment]
There we go! Can you please check 79d31b0 and b5d43cf ?

**Pull request merged**
